Temporarily..just....disable factory reset.

diff --git a/system_files/usr/share/tyrianos/scripts/admin-resettool b/system_files/usr/share/tyrianos/scripts/admin-resettool
--- a/system_files/usr/share/tyrianos/scripts/admin-resettool
+++ b/system_files/usr/share/tyrianos/scripts/admin-resettool
@@ -24,17 +24,18 @@ full_reset() {
 
 full_reset.confirmed() {
 	killall plasmashell || true
-	echo "-- Determining next boot's fate (Enabling initial setup)"
-	systemctl enable initial-setup
 	echo "-- Cleaning up mutations..."
 	rpm-ostree cleanup -m
 	echo "-- Aggressively deleting all users, even if still logged in... (We're restarting, this will not matter.)"
-	for u in $(awk -F: '$3 >= 1000 {print $1}' /etc/passwd); do userdel -r -f "$u"; done
+	for u in $(awk -F: '$3 >= 1000 {print $1}' /etc/passwd); do userdel -f -r "$u"; done || echo "Failure on removing users using userdel!?"
 	rm -rfv /home/* || true # in case users have been deleted but chose to keep their data
+	rm -rfv /var/mail/*	 || true # in case users have been deleted but chose to keep their data
 	echo "-- Wiping /etc (while preserving machine-id, hostname, fstab and crypttab.)"
 	find /etc -mindepth 1 -maxdepth 1 ! -name 'machine-id' ! -name 'hostname' ! -name 'fstab' ! -name 'crypttab' -exec rm -rf {} +
 	echo "-- Recreating /etc"
 	cp -rTv /usr/etc /etc
+	echo "-- Determining next boot's fate (Enabling initial setup)"
+	systemctl enable initial-setup
 	echo "-- To fully finish, TyrianOS will reboot in 10 seconds."
 	sleep 9
 	echo "-- Goodbye."
